sudo: required

services:
  - docker

script:
 - docker run --mount src=${TRAVIS_BUILD_DIR}/dir1,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic main.tex"
 - docker run --mount src=${TRAVIS_BUILD_DIR}/dir2,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic main.tex"
