sudo: required

services:
  - docker

script:
 - docker run --mount src=${TRAVIS_BUILD_DIR}/dir1,dst=/workdir,type=bind paperist/alpine-texlive-ja
  /bin/sh -c "latexmk -C main.tex"
 - docker run --mount src=${TRAVIS_BUILD_DIR}/dir2,dst=/workdir,type=bind paperist/alpine-texlive-ja
  /bin/sh -c "latexmk -C main.tex"

